elevenlabs:
  model: eleven_monolingual_v1
  voice_settings:
    similarity_boost: 0.85
    stability: 0.75
    style: 0.0
    use_speaker_boost: true
gemini:
  max_output_tokens: 8192
  model: gemini-1.5-flash
  temperature: 0.7
pdf:
  max_pages: 50
podcast:
  style: conversational
  target_duration_minutes: 10
  tone: engaging
